### ISSUE TITLE
AMX-IPComm Extension (.response event vs .receive)

### ISSUE THREAD

**Issue by DavidVine** [amx-itg/muse-demo-vandelay1527-js#1]
In the **Vandelay1527.js** example MUSE JavaScript program on the AMX ITG GitHub page it is using the AMX-IPComm Extension to connect to an AMX Precis switcher and the ```AMX-PR-WP-412.js``` file passes a callback listen to the ```response``` event:

```
PRECIS_WP_412.dv.response.listen(function(event){
PRECIS_WP_412.parse(String(event.arguments.data));
});
```

The **Vandelay1527.js** project references ```v1.0.0``` of the AMX-IPComm extension (```/Resources/Extensions/``` contains the ```AMX-IPComm-1.0.0.jar``` file).

The AMX-IPComm extension is available to download separately from the [muse-driver-amx-ipcomm repo](https://github.com/amx-itg/muse-driver-amx-ipcomm). The earliest version posted to this repository was ```v1.0.2``` but is currently at ```v1.0.3```.

I've found that while ```v1.0.0``` of the AMX-IPComm extension does have a ```response``` event this event has been renamed to ```receive``` in ```v1.0.2``` and ```v1.0.3``` (I'm guessing to align with the API used by other MUSE devices such as serial ports).

To avoid confusion from customers who might try to use example code taken from the **Vandelay1527.js** repository but have downloaded and installed the AMX-IPComm extension from the [muse-driver-amx-ipcomm repo](https://github.com/amx-itg/muse-driver-amx-ipcomm) repository might it be worth updating the **Vandelay1527.js** repository to reference the latest version of the AMX-IPComm extension (```AMX-IPComm-1.0.3.jar```) and modify the code to use the ```receive``` event for the Precis device? E.g:

```
PRECIS_WP_412.dv.receive.listen(function(event){
PRECIS_WP_412.parse(String(event.arguments.data));
});
```

**Comment by amx-itg** [comment]
AMX-PR-WP-412.js updated per request to match with 1.03 changes.

**Comment by DavidVine** [comment]
Thanks Ian.
